//
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
//
export const ADD_FAVORITE_SONG = "ADD_FAVORITE_SONG";
export const REMOVE_FAVORITE_SONG = "REMOVE_FAVORITE_SONG";