export const Types = {
  SEARCH_LOADING: 'SEARCH_LOADING',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_ERROR: 'SEARCH_ERROR',

  ADD_FAVORITE_SONG: 'ADD_FAVORITE_SONG',
  REMOVE_FAVORITE_SONG: 'REMOVE_FAVORITE_SONG',

  USER_LOADING: 'USER_LOADING',
  USER_SUCCESS: 'USER_SUCCESS',
  USER_ERROR: 'USER_ERROR',

  RELEASES_LOADING: 'RELEASES_LOADING',
  RELEASES_SUCCESS: 'RELEASES_SUCCESS',
  RELEASES_ERROR: 'RELEASES_ERROR',

  TESTE: 'USER/TESTE',
};
